# Generated by Django 5.2.3 on 2025-06-28 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenComplianceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('recommendation', models.CharField(choices=[('go', 'GO'), ('no_go', 'NO GO'), ('enhanced_due_diligence', 'Enhanced Due Diligence'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('flags', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_analysis', to='api.tokencomplianceprofile')),
            ],
        ),
    ]
