# Generated by Django 5.2.3 on 2025-06-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractanalysisresult',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.AddField(
            model_name='contractanalysisresult',
            name='bytecode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractanalysisresult',
            name='bytecode_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contractanalysisresult',
            name='engine_version',
            field=models.CharField(default='0.1-beta', max_length=16),
        ),
        migrations.AlterField(
            model_name='contractanalysisresult',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_analyses', to='api.tokencomplianceprofile'),
        ),
    ]
