# Generated by Django 5.2.3 on 2025-06-28 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_holderanalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolderAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=42, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.holder')),
            ],
        ),
        migrations.CreateModel(
            name='HolderTokenLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holder_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.holderaddress')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_links', to='api.tokencomplianceprofile')),
            ],
        ),
    ]
